    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.biblioteca.view;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.biblioteca.controller.AuthorController;
import org.biblioteca.controller.LoanController;
import org.biblioteca.controller.ResourcesController;
import org.biblioteca.controller.UserController;
import org.biblioteca.controller.SanctionController;
import org.biblioteca.controller.ApplySanctionController;


import org.biblioteca.model.ConsultasRecurso;
import org.biblioteca.model.Resources;
import org.biblioteca.model.Loan;
import org.biblioteca.model.User;
import org.biblioteca.model.Author;
import org.biblioteca.model.AuthorResource;
import org.biblioteca.model.UserConsults;
import org.biblioteca.model.LoanResources;
import org.biblioteca.model.Sanctions;
import org.biblioteca.model.SanctionsConsults;



//import org.biblioteca.view.RegisterAuthor;
//import org.biblioteca.view.RegisterUser;
/**
 *
 * @author 
 */
public class BasicMainPage extends javax.swing.JFrame implements MainPage{

    /**
     * Creates new form MainPage
     */
    
    public BasicMainPage() {
        initComponents();
        userRegister.setVisible(false);
        jButtonAuthor.setVisible(false);
        jButtonCategoria.setVisible(false);
        jButtonAplicarSanciones.setVisible(false);
        jButtonPosPrestamo.setVisible(false);
        jButtonReportes.setVisible(false);
        jButtonPrestamo.setVisible(false);
        jButtonSanciones.setVisible(false);
        errorLabel.setVisible(false);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBiblioteca = new javax.swing.JButton();
        userRegister = new javax.swing.JButton();
        jButtonAuthor = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButtonPrestamo = new javax.swing.JButton();
        jButtonPosPrestamo = new javax.swing.JButton();
        jButtonSanciones = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonAplicarSanciones = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBiblioteca.setText("Revisar Biblioteca");
        jButtonBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBibliotecaMouseClicked(evt);
            }
        });
        jButtonBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBibliotecaActionPerformed(evt);
            }
        });

        userRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userRegister.setText("Registrar Usuario");
        userRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRegisterMouseClicked(evt);
            }
        });
        userRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegisterActionPerformed(evt);
            }
        });

        jButtonAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAuthor.setText("Registrar Autor");
        jButtonAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAuthorMouseClicked(evt);
            }
        });
        jButtonAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthorActionPerformed(evt);
            }
        });

        jButtonCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCategoria.setText("Registrar Categoria");
        jButtonCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaActionPerformed(evt);
            }
        });

        jButtonPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPrestamo.setText("Solicitar Prestamo");
        jButtonPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrestamoMouseClicked(evt);
            }
        });
        jButtonPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrestamoActionPerformed(evt);
            }
        });

        jButtonPosPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPosPrestamo.setText("Devolucion");
        jButtonPosPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPosPrestamoActionPerformed(evt);
            }
        });

        jButtonSanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSanciones.setText("Revisar Sanciones");
        jButtonSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSancionesMouseClicked(evt);
            }
        });
        jButtonSanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSancionesActionPerformed(evt);
            }
        });

        jButtonReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonReportes.setText("Reportes");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });

        jButtonAplicarSanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAplicarSanciones.setText("Aplicar Sancion");
        jButtonAplicarSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAplicarSancionesMouseClicked(evt);
            }
        });
        jButtonAplicarSanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarSancionesActionPerformed(evt);
            }
        });

        errorLabel.setText("Error");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAplicarSanciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(errorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(errorLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(jButtonSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(userRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonAplicarSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegisterActionPerformed

    private void userRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisterMouseClicked
        RegisterUser view = new RegisterUser();
        User model = new User();
        UserConsults querys = new UserConsults();
        UserController user = new UserController(model, querys, view);
        view.setVisible(true);
    }//GEN-LAST:event_userRegisterMouseClicked

    private void jButtonPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrestamoActionPerformed

    private void jButtonPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrestamoMouseClicked
        LoanView view = new LoanView();
        Resources model = new Resources();
        Loan modelLoan = new Loan();
        LoanResources modelLoanReso = new LoanResources();
        ConsultasRecurso querys = new ConsultasRecurso();
        LoanController loanController = new LoanController(model,modelLoan,modelLoanReso,querys,view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPrestamoMouseClicked

    private void jButtonBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBibliotecaActionPerformed

    private void jButtonBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBibliotecaMouseClicked
        ResourcesManager view = new ResourcesManager();
        Resources model = new Resources();
        ConsultasRecurso querys = new ConsultasRecurso();
        ResourcesController resour = new ResourcesController(model, querys, view);
        view.setVisible(true);
        //view.setPositionRelativeTo(null);
    }//GEN-LAST:event_jButtonBibliotecaMouseClicked

    private void jButtonAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthorActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAuthorActionPerformed

    private void jButtonAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAuthorMouseClicked
        RegisterAuthor view = new RegisterAuthor();
        Resources model = new Resources();
        Author modelAuthor = new Author();
        AuthorResource modelAuthorResource = new AuthorResource();
        ConsultasRecurso querys = new ConsultasRecurso();
        AuthorController author = new AuthorController(model, modelAuthor, modelAuthorResource, querys, view);
        view.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAuthorMouseClicked

    private void jButtonSancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSancionesActionPerformed
    }//GEN-LAST:event_jButtonSancionesActionPerformed

    private void jButtonAplicarSancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarSancionesActionPerformed
    }//GEN-LAST:event_jButtonAplicarSancionesActionPerformed

    private void jButtonSancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSancionesMouseClicked
        SanctionView view = new SanctionView();
        Sanctions model = new Sanctions();
        SanctionsConsults querys = new SanctionsConsults();
        SanctionController sanction = new SanctionController(model,querys, view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonSancionesMouseClicked

    private void jButtonAplicarSancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAplicarSancionesMouseClicked
        ApplySanctionsView view = new ApplySanctionsView();
        Sanctions model = new Sanctions();
        SanctionsConsults querys = new SanctionsConsults();
        ApplySanctionController applysanction = new ApplySanctionController(model,querys,view);
        view.setVisible(true);

    }//GEN-LAST:event_jButtonAplicarSancionesMouseClicked

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCategoriaActionPerformed

    private void jButtonPosPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPosPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPosPrestamoActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton jButtonAplicarSanciones;
    public javax.swing.JButton jButtonAuthor;
    private javax.swing.JButton jButtonBiblioteca;
    public javax.swing.JButton jButtonCategoria;
    public javax.swing.JButton jButtonPosPrestamo;
    private javax.swing.JButton jButtonPrestamo;
    public javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonSanciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton userRegister;
    // End of variables declaration//GEN-END:variables


public JButton getjButtonBiblioteca() {
        return jButtonBiblioteca;
}
public JButton getjButtonPrestamo() {
        return jButtonPrestamo;
}

public JButton getUserRegister(){
        return userRegister;
}

public JButton getJButtonAuthor(){
        return jButtonAuthor;
}
public JButton getJButtonCategoria(){
        return jButtonCategoria;
        }

public JButton getJButtonAplicarSanciones(){
        return jButtonAplicarSanciones;
}

public JButton getJButtonPosPrestamo(){
        return jButtonPosPrestamo;
        }

public JButton getJButtonReportes(){
        return jButtonReportes;
}
        
public JButton getJButtonSanciones(){
        return jButtonSanciones;
}
        
public JLabel getErrorLabel(){
        return errorLabel;
}

public void enableButtons() { // No se habilitan botones adicionales al invitado
}

public void display() {
        this.setVisible(true);
    }
}
