/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.biblioteca.view;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JCheckBox;
//import com.toedter.calendar.JDateChooser;
import java.util.List;
import org.biblioteca.controller.ConexionController;

/**
 *
 * @author JESUS
 */
public class LoanView extends javax.swing.JFrame {
    private ConexionController cc;
    /**
     * Creates new form LoanView
     */
    public LoanView() {
        initComponents();
        cc = new ConexionController();
        fillComboBoxResourcesName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLoanTittle = new javax.swing.JLabel();
        ComboBoxResourcesName = new javax.swing.JComboBox<>();
        ComboBoxTypeResources = new javax.swing.JComboBox<>();
        LabelNameResources = new javax.swing.JLabel();
        LabelTypeResources = new javax.swing.JLabel();
        LabelLoanDate = new javax.swing.JLabel();
        LabelReturnDate = new javax.swing.JLabel();
        NoteCheckBox = new javax.swing.JCheckBox();
        LabelNote = new javax.swing.JLabel();
        ButtomLoan = new javax.swing.JButton();
        ButtomCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelLoanTittle.setText("PRESTAMOS");

        ComboBoxResourcesName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxResourcesNameActionPerformed(evt);
            }
        });

        ComboBoxTypeResources.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Video", "Audio", "Periodico" }));

        LabelNameResources.setText("Nombre del Recurso");

        LabelTypeResources.setText("Tipo del Recurso");

        LabelLoanDate.setText("Fecha del Prestamo");

        LabelReturnDate.setText("Fecha de Devolucion");

        NoteCheckBox.setText("Me comprometo a devolver el recurso antes o durante la fecha de devolcion");
        NoteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoteCheckBoxActionPerformed(evt);
            }
        });

        LabelNote.setText("DE NO DEVOLVER EL RECURSO, SE LE APLICARA UNA SANCION.");

        ButtomLoan.setText("Solicitar Prestamo");
        ButtomLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomLoanActionPerformed(evt);
            }
        });

        ButtomCancel.setText("Cancelar");
        ButtomCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtomCancelMouseClicked(evt);
            }
        });
        ButtomCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtomCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(LabelLoanDate)
                .addGap(94, 94, 94)
                .addComponent(LabelReturnDate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(LabelNote))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(LabelLoanTittle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ButtomLoan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtomCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(NoteCheckBox))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelNameResources)
                            .addComponent(LabelTypeResources))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxResourcesName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBoxTypeResources, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(LabelLoanTittle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTypeResources, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTypeResources))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNameResources)
                    .addComponent(ComboBoxResourcesName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelLoanDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelReturnDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(NoteCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelNote)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtomLoan)
                    .addComponent(ButtomCancel))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoteCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoteCheckBoxActionPerformed

    private void ButtomLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomLoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtomLoanActionPerformed

    private void ButtomCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtomCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtomCancelActionPerformed

    private void ButtomCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtomCancelMouseClicked
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtomCancelMouseClicked

    private void ComboBoxResourcesNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxResourcesNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxResourcesNameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtomCancel;
    public javax.swing.JButton ButtomLoan;
    public javax.swing.JComboBox<String> ComboBoxResourcesName;
    public javax.swing.JComboBox<String> ComboBoxTypeResources;
    private javax.swing.JLabel LabelLoanDate;
    private javax.swing.JLabel LabelLoanTittle;
    private javax.swing.JLabel LabelNameResources;
    private javax.swing.JLabel LabelNote;
    private javax.swing.JLabel LabelReturnDate;
    private javax.swing.JLabel LabelTypeResources;
    public javax.swing.JCheckBox NoteCheckBox;
    // End of variables declaration//GEN-END:variables
   
    
    
    public JButton getButtonCancel (){
            return ButtomCancel;
 }
    public JButton getButtonLoan (){
            return ButtomCancel;
 }
    public JComboBox getComboBoxResourcesName (){
            return ComboBoxResourcesName;
 }
    public JComboBox getComboBoxTypeResources (){
            return ComboBoxTypeResources;
 }
    public JCheckBox getNoteCheckBox (){
            return NoteCheckBox;
}
    /*public JDateChooser getDateChooserLoan (){
            return DateChooserLoan;
}
    public JDateChooser getDateChooserReturn (){
            return DateChooserReturn;      
}
*/
    void setPositionRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void fillComboBoxResourcesName() {
        List<String> datos = cc.obtenerDatos();
        for (String dato : datos) {
            ComboBoxResourcesName.addItem(dato);
        }
    }
}