    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.biblioteca.view;

import javax.swing.JButton;
import org.biblioteca.controller.AuthorController;
import org.biblioteca.controller.LoanController;
import org.biblioteca.controller.ResourcesController;
import org.biblioteca.controller.UserController;
import org.biblioteca.controller.SanctionController;
import org.biblioteca.controller.ApplySanctionController;
import org.biblioteca.controller.ReturnsController;


import org.biblioteca.model.ConsultasRecurso;
import org.biblioteca.model.Resources;
import org.biblioteca.model.Loan;
import org.biblioteca.model.User;
import org.biblioteca.model.Author;
import org.biblioteca.model.AuthorResource;
import org.biblioteca.model.UserConsults;
import org.biblioteca.model.LoanResources;
import org.biblioteca.model.Sanctions;
import org.biblioteca.model.SanctionsConsults;
import org.biblioteca.model.Return;
import org.biblioteca.model.ReturnConsults;



//import org.biblioteca.view.RegisterAuthor;
//import org.biblioteca.view.RegisterUser;
/**
 *
 * @author 
 */
public class MainPage extends javax.swing.JFrame {


    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBiblioteca = new javax.swing.JButton();
        userRegister = new javax.swing.JButton();
        jButtonAuthor = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButtonPrestamo = new javax.swing.JButton();
        jButtonPosPrestamo = new javax.swing.JButton();
        jButtonSanciones = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();
        jButtonAplicarSanciones = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBiblioteca.setText("Revisar Biblioteca");
        jButtonBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBibliotecaMouseClicked(evt);
            }
        });
        jButtonBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBibliotecaActionPerformed(evt);
            }
        });

        userRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userRegister.setText("Registrar Usuario");
        userRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRegisterMouseClicked(evt);
            }
        });
        userRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegisterActionPerformed(evt);
            }
        });

        jButtonAuthor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAuthor.setText("Registrar Autor");
        jButtonAuthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAuthorMouseClicked(evt);
            }
        });
        jButtonAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAuthorActionPerformed(evt);
            }
        });

        jButtonCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCategoria.setText("Registrar Categoria");

        jButtonPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPrestamo.setText("Solicitar Prestamo");
        jButtonPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrestamoMouseClicked(evt);
            }
        });
        jButtonPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrestamoActionPerformed(evt);
            }
        });

        jButtonPosPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPosPrestamo.setText("Devolucion");

        jButtonSanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonSanciones.setText("Revisar Sanciones");
        jButtonSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSancionesMouseClicked(evt);
            }
        });
        jButtonSanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSancionesActionPerformed(evt);
            }
        });

        jButtonReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonReportes.setText("Reportes");
        jButtonReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportesActionPerformed(evt);
            }
        });

        jButtonAplicarSanciones.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAplicarSanciones.setText("Aplicar Sancion");
        jButtonAplicarSanciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAplicarSancionesMouseClicked(evt);
            }
        });
        jButtonAplicarSanciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAplicarSancionesActionPerformed(evt);
            }
        });

        jButtonReturn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonReturn.setText("Devoluciones");
        jButtonReturn.setToolTipText("");
        jButtonReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonReturnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(605, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userRegister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAplicarSanciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReturn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(userRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAplicarSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSanciones, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegisterActionPerformed

    private void userRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisterMouseClicked
        RegisterUser view = new RegisterUser();
        User model = new User();
        UserConsults querys = new UserConsults();
        UserController user = new UserController(model, querys, view);
        view.setVisible(true);
    }//GEN-LAST:event_userRegisterMouseClicked

    private void jButtonPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrestamoActionPerformed

    private void jButtonPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrestamoMouseClicked
        LoanView view = new LoanView();
        Resources model = new Resources();
        Loan modelLoan = new Loan();
        LoanResources modelLoanReso = new LoanResources();
        ConsultasRecurso querys = new ConsultasRecurso();
        LoanController loanController = new LoanController(model,modelLoan,modelLoanReso,querys,view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPrestamoMouseClicked

    private void jButtonBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBibliotecaActionPerformed

    private void jButtonBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBibliotecaMouseClicked
        ResourcesManager view = new ResourcesManager();
        Resources model = new Resources();
        ConsultasRecurso querys = new ConsultasRecurso();
        ResourcesController resour = new ResourcesController(model, querys, view);
        view.setVisible(true);
        //view.setPositionRelativeTo(null);
    }//GEN-LAST:event_jButtonBibliotecaMouseClicked

    private void jButtonAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAuthorActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAuthorActionPerformed

    private void jButtonAuthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAuthorMouseClicked
        RegisterAuthor view = new RegisterAuthor();
        Resources model = new Resources();
        Author modelAuthor = new Author();
        AuthorResource modelAuthorResource = new AuthorResource();
        ConsultasRecurso querys = new ConsultasRecurso();
        AuthorController author = new AuthorController(model, modelAuthor, modelAuthorResource, querys, view);
        view.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAuthorMouseClicked

    private void jButtonSancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSancionesActionPerformed
    }//GEN-LAST:event_jButtonSancionesActionPerformed

    private void jButtonAplicarSancionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAplicarSancionesActionPerformed
    }//GEN-LAST:event_jButtonAplicarSancionesActionPerformed

    private void jButtonSancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSancionesMouseClicked
        SanctionView view = new SanctionView();
        Sanctions model = new Sanctions();
        SanctionsConsults querys = new SanctionsConsults();
        SanctionController sanction = new SanctionController(model,querys, view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonSancionesMouseClicked

    private void jButtonAplicarSancionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAplicarSancionesMouseClicked
        ApplySanctionsView view = new ApplySanctionsView();
        Sanctions model = new Sanctions();
        SanctionsConsults querys = new SanctionsConsults();
        ApplySanctionController applysanction = new ApplySanctionController(model,querys,view);
        view.setVisible(true);

    }//GEN-LAST:event_jButtonAplicarSancionesMouseClicked

    private void jButtonReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReportesActionPerformed

    private void jButtonReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonReturnMouseClicked
        ReturnView view = new ReturnView();
        Return model = new Return();
        ReturnConsults querys = new ReturnConsults();
        ReturnsController returnC = new ReturnsController(model,querys,view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonReturnMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAplicarSanciones;
    public javax.swing.JButton jButtonAuthor;
    private javax.swing.JButton jButtonBiblioteca;
    public javax.swing.JButton jButtonCategoria;
    public javax.swing.JButton jButtonPosPrestamo;
    private javax.swing.JButton jButtonPrestamo;
    public javax.swing.JButton jButtonReportes;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JButton jButtonSanciones;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton userRegister;
    // End of variables declaration//GEN-END:variables

public JButton getjButtonBiblioteca() {
        return jButtonBiblioteca;
}
public JButton getjButtonPrestamo() {
        return jButtonPrestamo;
}

public JButton getjButtonUserRegister() {
        return userRegister;
}

public JButton getjButtonAuthor() {
        return jButtonAuthor;
}
}
