    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.biblioteca.view;

import javax.swing.JButton;
import org.biblioteca.controller.LoanController;
import org.biblioteca.controller.ResourcesController;
import org.biblioteca.model.ConsultasRecurso;
import org.biblioteca.model.Resources;
import org.biblioteca.model.Loan;
import org.biblioteca.model.User;
import org.biblioteca.view.RegisterUser;
import org.biblioteca.controller.UserController;
import org.biblioteca.model.UserConsults;
import org.biblioteca.model.LoanResources;
/**
 *
 * @author Luzzio
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBiblioteca = new javax.swing.JButton();
        userRegister = new javax.swing.JButton();
        jButtonAutor = new javax.swing.JButton();
        jButtonCategoria = new javax.swing.JButton();
        jButtonPrestamo = new javax.swing.JButton();
        jButtonPosPrestamo = new javax.swing.JButton();
        jButtonReportes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonBiblioteca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBiblioteca.setText("Revisar Biblioteca");
        jButtonBiblioteca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBibliotecaMouseClicked(evt);
            }
        });
        jButtonBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBibliotecaActionPerformed(evt);
            }
        });

        userRegister.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userRegister.setText("Registrar Usuario");
        userRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRegisterMouseClicked(evt);
            }
        });
        userRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userRegisterActionPerformed(evt);
            }
        });

        jButtonAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonAutor.setText("Registrar Autor");
        jButtonAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutorActionPerformed(evt);
            }
        });

        jButtonCategoria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonCategoria.setText("Registrar Categoria");

        jButtonPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPrestamo.setText("Solicitar Prestamo");
        jButtonPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPrestamoMouseClicked(evt);
            }
        });
        jButtonPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrestamoActionPerformed(evt);
            }
        });

        jButtonPosPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonPosPrestamo.setText("Devolucion");

        jButtonReportes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonReportes.setText("Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(600, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPrestamo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(userRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBiblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonPosPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userRegisterActionPerformed

    private void userRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisterMouseClicked
        RegisterUser view = new RegisterUser();
        User model = new User();
        UserConsults querys = new UserConsults();
        UserController user = new UserController(model, querys, view);
        view.setVisible(true);
    }//GEN-LAST:event_userRegisterMouseClicked

    private void jButtonPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrestamoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPrestamoActionPerformed

    private void jButtonPrestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPrestamoMouseClicked
        LoanView view = new LoanView();
        Resources model = new Resources();
        Loan modelLoan = new Loan();
        LoanResources modelLoanReso = new LoanResources();
        ConsultasRecurso querys = new ConsultasRecurso();
        LoanController loanController = new LoanController(model,modelLoan,modelLoanReso,querys,view);
        view.setVisible(true);
    }//GEN-LAST:event_jButtonPrestamoMouseClicked

    private void jButtonBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBibliotecaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBibliotecaActionPerformed

    private void jButtonBibliotecaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBibliotecaMouseClicked
        ResourcesManager view = new ResourcesManager();
        Resources model = new Resources();
        ConsultasRecurso querys = new ConsultasRecurso();
        ResourcesController resour = new ResourcesController(model, querys, view);
        view.setVisible(true);
        //view.setPositionRelativeTo(null);
    }//GEN-LAST:event_jButtonBibliotecaMouseClicked

    private void jButtonAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAutor;
    private javax.swing.JButton jButtonBiblioteca;
    public javax.swing.JButton jButtonCategoria;
    public javax.swing.JButton jButtonPosPrestamo;
    private javax.swing.JButton jButtonPrestamo;
    public javax.swing.JButton jButtonReportes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton userRegister;
    // End of variables declaration//GEN-END:variables

public JButton getjButtonBiblioteca() {
        return jButtonBiblioteca;
}
public JButton getjButtonPrestamo() {
        return jButtonPrestamo;
}
}
